### ISSUE TITLE
SirMenswats#2505

### ISSUE THREAD

**Issue by Thunderbelly4** [discordlinux/rules#10]
### What is your username and discriminator?
SirMenswats#2505

### Why did you join Discord Linux?
Gain help with some of my ubuntu issues

### Where did you hear about Discord Linux?
discord.me

### What is the passphrase that was assigned to you by the bot?
I cant figure it out. 🤷‍♂️

**Comment by Thunderbelly4** [comment]
I figured out my passphrase. sorry I was stupid and over read it. s﻿u﻿d﻿o﻿ ﻿-﻿i﻿ ﻿waistband﻿-﻿condominium﻿-﻿goofy﻿-﻿sea

**Comment by Vixtron** [comment]
This issue is closed.

**Comment by Thunderbelly4** [comment]
I cant verify via phone. -_-

**Comment by Vixtron** [comment]
You've been given a temporary role.
