### ISSUE TITLE
GunqqerFriithian non-phone verification

### ISSUE THREAD

**Issue by gunqqer** [discordlinux/rules#13]
### What is your username and discriminator?
Gunqqer Friithian#1502

### Why did you join Discord Linux?
To talk about linux (specifically VM stuff and USB passthrough)

### Where did you hear about Discord Linux?
Another Discord server

### What is the passphrase that was assigned to you by the bot?
﻿changeable﻿-﻿become﻿-﻿penicillin﻿-﻿chew

**Comment by simoniz0r** [comment]
Looks good.  I've given you a temporary role so you may enter the passphrase.
