### ISSUE TITLE
Request to get in, I do not have a phone

### ISSUE THREAD

**Issue by JTJSniperBee** [discordlinux/rules#14]
### What is your username and discriminator?
Senhara Jenaine#5373

### Why did you join Discord Linux?
To get help with Debian-based Linux OSes and to learn some things about Linux

### Where did you hear about Discord Linux?
I googled for Linux Discord Server

### What is the passphrase that was assigned to you by the bot?
note﻿-﻿trial﻿-﻿craven﻿-﻿employer

**Comment by simoniz0r** [comment]
Looks good.  I'll give you a temp role so you can enter the passphrase.
