### ISSUE TITLE
Tetros#0704 / I joined to learn more about Linux as I just intsalled my first Distro. / I heard about it from Discord.Me while searching for a community on Discord. / I don't have a phone for the passphrase.

### ISSUE THREAD

**Issue by TetrosNagami** [discordlinux/rules#16]

**Comment by sansation** [comment]
Please read over the description the bot outputted when you joined the server. The passphrase is in the link you've been given, so please look over that page and reply with it here.

**Comment by Vixtron** [comment]
Used the template incorrectly.

**Comment by Vixtron** [comment]
If you still have the issue please resubmit it using the correct format.
