### ISSUE TITLE
Here's my submission Discord

### ISSUE THREAD

**Issue by IndigoAjax** [discordlinux/rules#164]
### What is your username and discriminator?
@linuxUser#4004

### Why did you join Discord Linux?
Cos TUX IS THE BEST, also i use linux and i wanted to know what was going on in the server

### Where did you hear about Discord Linux?
discord.gg/discord-developers

### What is the passphrase that was assigned to you by the bot?
q2v7j3tkwbtjv

**Comment by simoniz0r** [comment]
Closing as it has been more than 24 hours.
