### ISSUE TITLE
i cant passphrase right

### ISSUE THREAD

**Issue by suomilanittaja** [discordlinux/rules#18]
### What is your username and discriminator?
suomilanittaja

### Why did you join Discord Linux?
becouse i use linux

### Where did you hear about Discord Linux?
i found it from scanning internet

### What is the passphrase that was assigned to you by the bot?
505696148070087517
maybe this i didnt understand what it really meaned

**Comment by simoniz0r** [comment]
This form is for people who do not have a phone to verify with Discord.  Please read the embed that mentions you in the welcome channel.
