### ISSUE TITLE
181833552936042497

### ISSUE THREAD

**Issue by Chaoss86** [discordlinux/rules#20]
### What is your username and discriminator?
Chaoss#5496

### Why did you join Discord Linux?
Need help (I haven't really updated linux since early 2000's was using a very old rig, now built a new one and im stuck)

### Where did you hear about Discord Linux?
google (and the irc, which has sadly closed down)

### What is the passphrase that was assigned to you by the bot?
181833552936042497

**Comment by Vixtron** [comment]
The passphrase is not your user ID. Read the contents of this [url](https://blargbot.xyz/output/507006254552464928), source is the welcome embed.
