### ISSUE TITLE
Join and support. 

### ISSUE THREAD

**Issue by violetrose16** [discordlinux/rules#41]
### What is your username and discriminator?
violetrose19#9893

### Why did you join Discord Linux?
I am joined Discord Linux because I am asking for support and install Linux problem. 

### Where did you hear about Discord Linux?
I looked for discord Linux server from google.ca 

### What is the passphrase that was assigned to you by the bot?
sudo -i made-the-game-design

**Comment by simoniz0r** [comment]
Sorry, I completely missed this submission.  If you'd still like to join, please make another submission.
