### ISSUE TITLE
624ft

### ISSUE THREAD

**Issue by 624ft** [discordlinux/rules#45]
### What is your username and discriminator?
@624ft#0624

### Why did you join Discord Linux?
To gain a better understanding of Discord Linux, as it is very difficult for me to run Discord on a Linux distro.

### Where did you hear about Discord Linux?
https://discord.gg/developers (Discord Developers Server)

### What is the passphrase that was assigned to you by the bot?
Excuse me, but I do not see a passphrase.

**Comment by simoniz0r** [comment]
Closing as it has been more than 24 hours.
