### ISSUE TITLE
Discord no phone

### ISSUE THREAD

**Issue by Blayyke** [discordlinux/rules#7]
### What is your username and discriminator?
Blayyke#8221

### Why did you join Discord Linux?
Keep up with discord news

### Where did you hear about Discord Linux?
/r/discordapp on reddit 

### What is the passphrase that was assigned to you by the bot?
sudo -i category-scheme-dune buggy-joyous

**Comment by simoniz0r** [comment]
Looks good.  I gave you a temporary role so you can enter the passphrase.
