### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by LezZJI** [discordlinux/rules#8]
### What is your username and discriminator?
LezZJI#1881

### Why did you join Discord Linux?
for chat and helping

### Where did you hear about Discord Linux?
in DTHS

### What is the passphrase that was assigned to you by the bot?
where i get mine ???

**Comment by simoniz0r** [comment]
Right on the same page that you found the link for this form.  Seeing as you totally have your phone verified with Discord, I'm just gonna go ahead and close this.
