### ISSUE TITLE
discord server application (no phone service)

### ISSUE THREAD

**Issue by jcarter777** [discordlinux/rules#94]
### What is your username and discriminator?
chmod 777#7144

### Why did you join Discord Linux?
linux enthusiast, full-time user

### Where did you hear about Discord Linux?
"linux" search on discord server list

### What is the passphrase that was assigned to you by the bot?
Glory to the Tux

**Comment by simoniz0r** [comment]
If you open one more issue, I will ban you from Discord Linux.
